### ISSUE TITLE
Loading data batch wise?

### ISSUE THREAD

**Issue by GeoffNN** [fra31/auto-attack#32]
Hi, and thanks for open-sourcing your code!

My machine has a memory error when running evaluation scripts on several models ; it looks like the load_cifar10 function (and others) load the full dataset in memory, and then iterates over the tensor. Am I correct, or is there a way of loading the data sequentially to gpu?

Thanks!

**Comment by fra31** [comment]
Hi!

I don't think there's such function in this repository. Do you maybe refer to [this](https://github.com/RobustBench/robustbench/blob/3e83f50f494b4c0548de82fb400ded0045b64614/robustbench/data.py#L10) from [RobustBench](https://github.com/RobustBench/robustbench)? If yes, you're right, all the points are loaded to the GPU. This is indeed suboptimal and is going to be fixed.

Temporarily, it should be enough to change [this](https://github.com/RobustBench/robustbench/blob/3e83f50f494b4c0548de82fb400ded0045b64614/robustbench/data.py#L26) line, removing `.cuda()`, since anyway the batches are loaded to GPU individually before inference [here](https://github.com/RobustBench/robustbench/blob/3e83f50f494b4c0548de82fb400ded0045b64614/robustbench/utils.py#L94).

For AutoAttack, the loading to the GPU already happens batchwise, and the dataset is stored on the CPU only (as in [this](https://github.com/fra31/auto-attack/blob/master/autoattack/examples/eval.py) example).

Let me know if this helps!

**Comment by fra31** [comment]
Hi,

This should be fixed by https://github.com/RobustBench/robustbench/pull/1.

**Comment by GeoffNN** [comment]
Great, thanks!
