### ISSUE TITLE
What should be reported, the average of results or the minimum?

### ISSUE THREAD

**Issue by Hrushikesh-github** [fra31/auto-attack#45]
Firstly, thank you very much for this repo, it is very helpful. 

I performed the AA attack on my model and got the following results:
```
robust accuracy by APGD-CE 28.00% 	 (time attack: 6.2 s)
robust accuracy by APGD-T 	 36.00% 	 (time attack: 15.6 s)
robust accuracy by FAB-T 	 92.00% 	 (time attack: 76.9 s)
robust accuracy by SQUARE 	 65.00% 	 (time attack: 67.5 s)
```

The average yields 55.25 but the minimum is 28. So what should be reported as the accuracy of the model on AutoAttack?

Also, out of curiousity, most of the models shown in the leaderboard are from the ResNet family of architectures with one densenet network. The AutoAttack can even be used for other architectures like VGG right?

**Comment by fra31** [comment]
Hi,

glad to hear that AutoAttack is helpful!

One should report the pointwise worst case over the four attacks, that is if any of the attacks is successful on an input, that input is considered non robust. In your cases, the robust accuracy will be no more than 28%, but likely lower, since it happens that different attacks succeed on different points. Note that this is automatically computed using ```x_adv = adversary.run_standard_evaluation(images, labels)```.

AA can be used on any architecture, just ResNets are more popular currently.

Hope this helps!
